### ISSUE TITLE
There is windows portable link on the site, doesn't go anywhere #

### ISSUE THREAD

**Issue by rgfx** [elzoughby/vdm#16]
FYI

**Comment by elzoughby** [comment]
Yes I know☺️
It will be available with the final version.

**Comment by smaragdus** [comment]
I would appreciate portable version of the program. By portable version I mean:

- download the archive;
- extract the archive;
- run the executable;
- data and settings saved in program folder;

nothing written to AppData folder, to User profile folder, to Windows Registry.
